apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oc-demo-projects
  namespace: flux-system
spec:
  interval: 5m
  path: ./namespaces/default/projects
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: sample-gitops
  dependsOn:
    - name: oc-demo-platform
